In [14]:
import pandas as pd
from collections import Counter

In [ ]:
df = pd.read_csv("../data/merged_labels.csv")
df

,job_id,title,text_final,isco_Lars,isco_Leander,isco_Leon,isco_Philipp
0,96,Veterinarian Medical Director J180570,Our client is looking for a Veterinarian Medic...,225.0,225.0,NaN,225.0
1,210,"Manager, Financial Planning and Analysis - Hyb...","Logistics at full potential. At [ORG], we’re c...",241.0,NaN,121.0,121.0
2,214,Inside Sales Representative - (PST Hours),Position [ORG] [ORG] is seeking an Inside Sale...,NaN,243.0,332.0,243.0
3,217,Travel - Telemetry - Nurse Job - $2440/wk - $2...,[ORG] has an immediate opening for the followi...,222.0,NaN,222.0,222.0
4,250,Checker Operator 2nd shift,Essential Duties And Responsibilities Individu...,834.0,NaN,432.0,834.0
...,...,...,...,...,...,...,...
735,30378,Opportunity for Private Practice therapist,[ORG] is seeking a licensed therapist to join ...,263.0,263.0,NaN,263.0
736,30443,Central Oklahoma Independent Retail - Sales Re...,[ORG] is a fourteen-year-old production/packag...,332.0,332.0,243.0,NaN
737,30454,General Manager,[ORG] is now hiring a General Manager at our S...,132.0,143.0,143.0,NaN
738,30469,Emergency Veterinarian,Orange County [ORG] is looking for a full-time...,225.0,225.0,225.0,NaN
739,30495,Director of Safety,"[ORG] Responsible for managing the safety, com...",132.0,NaN,132.0,121.0

In [16]:
label_cols = ["isco_Lars", "isco_Leander", "isco_Leon", "isco_Philipp"]

def majority_vote(row):
    votes = [str(row[c]) for c in label_cols if pd.notna(row[c])]

    if not votes:
        return "check"
    
    count = Counter(votes)

    top_code, top_n = count.most_common(1)[0]

    if top_n > len(votes) / 2:
        return top_code
    else:
        return "check"

df["isco_final"] = df.apply(majority_vote, axis=1)
df

,job_id,title,text_final,isco_Lars,isco_Leander,isco_Leon,isco_Philipp,isco_final
0,96,Veterinarian Medical Director J180570,Our client is looking for a Veterinarian Medic...,225.0,225.0,NaN,225.0,225.0
1,210,"Manager, Financial Planning and Analysis - Hyb...","Logistics at full potential. At [ORG], we’re c...",241.0,NaN,121.0,121.0,121.0
2,214,Inside Sales Representative - (PST Hours),Position [ORG] [ORG] is seeking an Inside Sale...,NaN,243.0,332.0,243.0,243.0
3,217,Travel - Telemetry - Nurse Job - $2440/wk - $2...,[ORG] has an immediate opening for the followi...,222.0,NaN,222.0,222.0,222.0
4,250,Checker Operator 2nd shift,Essential Duties And Responsibilities Individu...,834.0,NaN,432.0,834.0,834.0
...,...,...,...,...,...,...,...,...
735,30378,Opportunity for Private Practice therapist,[ORG] is seeking a licensed therapist to join ...,263.0,263.0,NaN,263.0,263.0
736,30443,Central Oklahoma Independent Retail - Sales Re...,[ORG] is a fourteen-year-old production/packag...,332.0,332.0,243.0,NaN,332.0
737,30454,General Manager,[ORG] is now hiring a General Manager at our S...,132.0,143.0,143.0,NaN,143.0
738,30469,Emergency Veterinarian,Orange County [ORG] is looking for a full-time...,225.0,225.0,225.0,NaN,225.0
739,30495,Director of Safety,"[ORG] Responsible for managing the safety, com...",132.0,NaN,132.0,121.0,132.0

In [17]:
print(df["isco_final"].value_counts().get("check", 0), "Cases to check")

58 Cases to check

In [ ]:
df.to_excel("../data/gold_standard_labels_final.xlsx", index=False)

### Upload Excel with final labels (majority and llm)

In [ ]:
df_final = pd.read_excel("../data/gold_standard_labels_done.xlsx")
df_final

,job_id,title,text_final,isco_Lars,isco_Leander,isco_Leon,isco_Philipp,isco_final,isco
0,96,Veterinarian Medical Director J180570,Our client is looking for a Veterinarian Medic...,225.0,225.0,NaN,225.0,225.0,225.0
1,210,"Manager, Financial Planning and Analysis - Hyb...","Logistics at full potential. At [ORG], we’re c...",241.0,NaN,121.0,121.0,121.0,121.0
2,214,Inside Sales Representative - (PST Hours),Position [ORG] [ORG] is seeking an Inside Sale...,NaN,243.0,332.0,243.0,243.0,243.0
3,217,Travel - Telemetry - Nurse Job - $2440/wk - $2...,[ORG] has an immediate opening for the followi...,222.0,NaN,222.0,222.0,222.0,222.0
4,250,Checker Operator 2nd shift,Essential Duties And Responsibilities Individu...,834.0,NaN,432.0,834.0,834.0,834.0
...,...,...,...,...,...,...,...,...,...
735,30378,Opportunity for Private Practice therapist,[ORG] is seeking a licensed therapist to join ...,263.0,263.0,NaN,263.0,263.0,263.0
736,30443,Central Oklahoma Independent Retail - Sales Re...,[ORG] is a fourteen-year-old production/packag...,332.0,332.0,243.0,NaN,332.0,332.0
737,30454,General Manager,[ORG] is now hiring a General Manager at our S...,132.0,143.0,143.0,NaN,143.0,143.0
738,30469,Emergency Veterinarian,Orange County [ORG] is looking for a full-time...,225.0,225.0,225.0,NaN,225.0,225.0
739,30495,Director of Safety,"[ORG] Responsible for managing the safety, com...",132.0,NaN,132.0,121.0,132.0,132.0

In [ ]:
df_isco = df_final[["job_id", "title", "text_final", "isco"]]
df_isco["isco"] = df_isco["isco"].astype(int).astype(str)
df_isco.to_csv("../data/labeled.csv", index = None)

### Create unlabeled.csv

In [ ]:
df_labeled = pd.read_csv("../data/labeled.csv")
df_unlabeled = pd.read_parquet("../job_ads_cleaned.parquet").reset_index(drop=True)
df_unlabeled["job_id"] = df_unlabeled.index

In [22]:
df_unlabeled = df_unlabeled[["job_id", "title", "text_final"]]
df_unlabeled["isco"] = pd.NA
df_unlabeled

,job_id,title,text_final,isco
0,0,Hearing Care Provider,Overview HearingLife is a national hearing car...,<NA>
1,1,Shipping & Receiving Associate 2nd shift (Beav...,[ORG] of [ORG] of Mayville is an Equal Opportu...,<NA>
2,2,"Manager, Engineering",The [ORG] name is synonymous with excellence i...,<NA>
3,3,Cook,descriptionTitle Looking for a great opportuni...,<NA>
4,4,Principal Cloud Security Architect (Remote),"Job Summary At [ORG], we are on a mission to m...",<NA>
...,...,...,...,...
30582,30582,Sales Manager,Are you a dynamic and creative marketing profe...,<NA>
30583,30583,Office Administrative Assistant,"A fast-fashion wholesaler, is looking for a fu...",<NA>
30584,30584,Franchise Owner,[ORG] is a dryer and A/C – heat vent clean out...,<NA>
30585,30585,Licensed Insurance Agent,While many industries were hurt by the last fe...,<NA>
30586,30586,Stylist/ Clorist,[PERSON] is looking for an awesome experienced...,<NA>

In [ ]:
df_unlabeled = df_unlabeled[~df_unlabeled["job_id"].isin(df_labeled["job_id"])].copy()
df_unlabeled.to_parquet("../data/unlabeled.parquet", index = None)